using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using TesteDevExpress.Models;

namespace TesteDevExpress.Controllers
{
    [Route("api/[controller]/[action]")]
    public class FornecedoresController : Controller
    {
        private readonly AppDbContext _context;

        public FornecedoresController(AppDbContext context) {
            this._context = context;
        }

        [HttpGet]
        public IActionResult Get(DataSourceLoadOptions loadOptions) {
            //var fornecedores = _context.Fornecedores.Select(i => new {
            //    i.Id,
            //    i.Nome,
            //    i.Ativo
            //});

            var fornecedores = new List<Fornecedores>() {
                new Fornecedores { Id = 1, Nome = "1", Ativo = true },
new Fornecedores { Id = 2, Nome = "2", Ativo = true },
new Fornecedores { Id = 3, Nome = "Sadia", Ativo = true },
new Fornecedores { Id = 4, Nome = "BRF", Ativo = true },
new Fornecedores { Id = 5, Nome = "Aberden", Ativo = true },
new Fornecedores { Id = 6, Nome = "Actual", Ativo = true },
new Fornecedores { Id = 7, Nome = "Agranor", Ativo = true },
new Fornecedores { Id = 8, Nome = "Fraiburgo", Ativo = true },
new Fornecedores { Id = 9, Nome = "Alum.Nobre", Ativo = true },
new Fornecedores { Id = 10, Nome = "Apis Jordans", Ativo = true },
new Fornecedores { Id = 11, Nome = "Araujo Matheus", Ativo = true },
new Fornecedores { Id = 12, Nome = "Arcom", Ativo = true },
new Fornecedores { Id = 13, Nome = "Abijaude", Ativo = true },
new Fornecedores { Id = 14, Nome = "Asa", Ativo = true },
new Fornecedores { Id = 15, Nome = "Atende", Ativo = true },
new Fornecedores { Id = 16, Nome = "Atual", Ativo = true },
new Fornecedores { Id = 17, Nome = "Avinor", Ativo = true },
new Fornecedores { Id = 18, Nome = "W Nazareth", Ativo = true },
new Fornecedores { Id = 19, Nome = "Bacardi", Ativo = true },
new Fornecedores { Id = 20, Nome = "São Benedito", Ativo = true },
new Fornecedores { Id = 21, Nome = "BM Alimentos", Ativo = true },
new Fornecedores { Id = 22, Nome = "Bocaiuva", Ativo = true },
new Fornecedores { Id = 23, Nome = "Bombril", Ativo = true },
new Fornecedores { Id = 24, Nome = "Adenil", Ativo = true },
new Fornecedores { Id = 25, Nome = "Bunge", Ativo = true },
new Fornecedores { Id = 26, Nome = "Barbosa Marques", Ativo = true },
new Fornecedores { Id = 27, Nome = "Pandurata", Ativo = true },
new Fornecedores { Id = 133, Nome = "M.Dias Pelagio/fortaleza", Ativo = true },
new Fornecedores { Id = 134, Nome = "Vitão", Ativo = true },
new Fornecedores { Id = 135, Nome = "Uni Comercio", Ativo = true },
new Fornecedores { Id = 136, Nome = "Canção", Ativo = true },
new Fornecedores { Id = 137, Nome = "Coco Vale", Ativo = true },
new Fornecedores { Id = 138, Nome = "Danarf", Ativo = true },
new Fornecedores { Id = 139, Nome = "Yoki", Ativo = true },
new Fornecedores { Id = 140, Nome = "M.Cerealista", Ativo = true },
new Fornecedores { Id = 141, Nome = "Eliene Alves", Ativo = true },
new Fornecedores { Id = 142, Nome = "Joaquim Ort.", Ativo = true },
new Fornecedores { Id = 143, Nome = "Paraíba Frutas", Ativo = true },
new Fornecedores { Id = 144, Nome = "Gê-Jota", Ativo = true },
new Fornecedores { Id = 146, Nome = "JBS", Ativo = true },
new Fornecedores { Id = 147, Nome = "Norsa", Ativo = true },
new Fornecedores { Id = 148, Nome = "Boa Hora", Ativo = true },
new Fornecedores { Id = 149, Nome = "Mauricéa", Ativo = true },
new Fornecedores { Id = 150, Nome = "Dinap", Ativo = true },
new Fornecedores { Id = 151, Nome = "CRBS", Ativo = true },
new Fornecedores { Id = 152, Nome = "J.Souza", Ativo = true },
new Fornecedores { Id = 153, Nome = "Javan", Ativo = true },
new Fornecedores { Id = 154, Nome = "Veneza", Ativo = true },
new Fornecedores { Id = 155, Nome = "Latic.Sol", Ativo = true },
new Fornecedores { Id = 156, Nome = "Tchibum", Ativo = true },
new Fornecedores { Id = 157, Nome = "Jenival", Ativo = true },
new Fornecedores { Id = 158, Nome = "Itabone", Ativo = true },
new Fornecedores { Id = 159, Nome = "PIF PAF", Ativo = true },
new Fornecedores { Id = 160, Nome = "Saudali", Ativo = true },
new Fornecedores { Id = 161, Nome = "Difruta", Ativo = true },
new Fornecedores { Id = 162, Nome = "Nutricau", Ativo = true },
new Fornecedores { Id = 163, Nome = "Amaralina", Ativo = true },
new Fornecedores { Id = 172, Nome = "Alvalarde", Ativo = true },
new Fornecedores { Id = 173, Nome = "Motrisa", Ativo = true },
new Fornecedores { Id = 174, Nome = "Itambé", Ativo = true },
new Fornecedores { Id = 175, Nome = "Pedra Preta", Ativo = true },
new Fornecedores { Id = 176, Nome = "Café Bahia", Ativo = true },
new Fornecedores { Id = 177, Nome = "Dinâmica", Ativo = true },
new Fornecedores { Id = 178, Nome = "Interbrilho", Ativo = true },
new Fornecedores { Id = 179, Nome = "CM Distribuidora", Ativo = true },
new Fornecedores { Id = 180, Nome = "Perelo", Ativo = true },
new Fornecedores { Id = 181, Nome = "Zecas", Ativo = true },
new Fornecedores { Id = 182, Nome = "Vesper", Ativo = true },
new Fornecedores { Id = 183, Nome = "Teiu", Ativo = true },
new Fornecedores { Id = 184, Nome = "Cooperja", Ativo = true },
new Fornecedores { Id = 185, Nome = "Três Corações", Ativo = true },
new Fornecedores { Id = 186, Nome = "Casa Padim", Ativo = true },
new Fornecedores { Id = 187, Nome = "Sora", Ativo = true },
new Fornecedores { Id = 188, Nome = "Sul Bahia", Ativo = true },
new Fornecedores { Id = 189, Nome = "Limpano", Ativo = true },
new Fornecedores { Id = 190, Nome = "Mastter", Ativo = true },
new Fornecedores { Id = 191, Nome = "Com.Marguti", Ativo = true },
new Fornecedores { Id = 192, Nome = "Superbom", Ativo = true },
new Fornecedores { Id = 193, Nome = "P e L Agroindustria", Ativo = true },
new Fornecedores { Id = 194, Nome = "Raimundo Fonte", Ativo = true },
new Fornecedores { Id = 195, Nome = "Chocosul", Ativo = true },
new Fornecedores { Id = 196, Nome = "Tia Sonia", Ativo = true },
new Fornecedores { Id = 197, Nome = "Ind. Alim. do vale", Ativo = true },
new Fornecedores { Id = 198, Nome = "Ramilton", Ativo = true },
new Fornecedores { Id = 199, Nome = "Moin. paqueta", Ativo = true },
new Fornecedores { Id = 200, Nome = "Perf. dana", Ativo = true },
new Fornecedores { Id = 201, Nome = "Martins", Ativo = true },
new Fornecedores { Id = 202, Nome = "Codical", Ativo = true },
new Fornecedores { Id = 203, Nome = "Inbahia", Ativo = true },
new Fornecedores { Id = 204, Nome = "A Brito", Ativo = true },
new Fornecedores { Id = 205, Nome = "Jeane", Ativo = true },
new Fornecedores { Id = 206, Nome = "Urbano", Ativo = true },
new Fornecedores { Id = 207, Nome = "Unilever", Ativo = true },
new Fornecedores { Id = 208, Nome = "Seara", Ativo = true },
new Fornecedores { Id = 209, Nome = "Naturaves", Ativo = true },
new Fornecedores { Id = 210, Nome = "ELO", Ativo = true },
new Fornecedores { Id = 211, Nome = "Pescaria", Ativo = true },
new Fornecedores { Id = 212, Nome = "Soberano", Ativo = true },
new Fornecedores { Id = 213, Nome = "São Roque", Ativo = true },
new Fornecedores { Id = 214, Nome = "Matos Gama", Ativo = true },
new Fornecedores { Id = 215, Nome = "Util Kiko", Ativo = true },
new Fornecedores { Id = 216, Nome = "Pontual", Ativo = true },
new Fornecedores { Id = 217, Nome = "Latic. Mariana", Ativo = true },
new Fornecedores { Id = 218, Nome = "Cargill", Ativo = true },
new Fornecedores { Id = 219, Nome = "Micos", Ativo = true },
new Fornecedores { Id = 220, Nome = "Unisul", Ativo = true },
new Fornecedores { Id = 221, Nome = "J. Machado", Ativo = true },
new Fornecedores { Id = 222, Nome = "Saltega", Ativo = true },
new Fornecedores { Id = 223, Nome = "Lat Bela Vista", Ativo = true },
new Fornecedores { Id = 224, Nome = "Flor do Vale", Ativo = true },
new Fornecedores { Id = 225, Nome = "J. Maria Fajado", Ativo = true },
new Fornecedores { Id = 226, Nome = "J. Macedo", Ativo = true },
new Fornecedores { Id = 227, Nome = "Mili", Ativo = true },
new Fornecedores { Id = 228, Nome = "Idalicio", Ativo = true },
new Fornecedores { Id = 229, Nome = "JOSAPAR", Ativo = true },
new Fornecedores { Id = 230, Nome = "Leite Sol", Ativo = true },
new Fornecedores { Id = 231, Nome = "Grapiuna", Ativo = true },
new Fornecedores { Id = 232, Nome = "Marcschall", Ativo = true },
new Fornecedores { Id = 233, Nome = "Condor", Ativo = true },
new Fornecedores { Id = 234, Nome = "Latic. Tirolez", Ativo = true },
new Fornecedores { Id = 235, Nome = "Palmeira Latc.", Ativo = true },
new Fornecedores { Id = 236, Nome = "Guanabara", Ativo = true },
new Fornecedores { Id = 237, Nome = "Itabom", Ativo = true },
new Fornecedores { Id = 238, Nome = "Bom Sabor", Ativo = true },
new Fornecedores { Id = 239, Nome = "Santer", Ativo = true },
new Fornecedores { Id = 240, Nome = "Kibon", Ativo = true },
new Fornecedores { Id = 241, Nome = "Avigran", Ativo = true },
new Fornecedores { Id = 242, Nome = "Gelo Ita", Ativo = true },
new Fornecedores { Id = 243, Nome = "Ambev", Ativo = true },
new Fornecedores { Id = 244, Nome = "Peterfrut", Ativo = true },
new Fornecedores { Id = 245, Nome = "Coca Cola", Ativo = true },
new Fornecedores { Id = 246, Nome = "Discarne", Ativo = true },
new Fornecedores { Id = 247, Nome = "Comolimpa", Ativo = true },
new Fornecedores { Id = 248, Nome = "Marcos Antonio", Ativo = true },
new Fornecedores { Id = 249, Nome = "Bisc. São Benedito", Ativo = true },
new Fornecedores { Id = 250, Nome = "Cafe Paqueta", Ativo = true },
new Fornecedores { Id = 251, Nome = "L A L", Ativo = true },
new Fornecedores { Id = 252, Nome = "Ilpisa", Ativo = true },
new Fornecedores { Id = 253, Nome = "Cicp", Ativo = true },
new Fornecedores { Id = 254, Nome = "Marilan", Ativo = true },
new Fornecedores { Id = 255, Nome = "Goias Verde", Ativo = true },
new Fornecedores { Id = 256, Nome = "Nestle", Ativo = true },
new Fornecedores { Id = 257, Nome = "Indaia", Ativo = true },
new Fornecedores { Id = 258, Nome = "Unimarka", Ativo = true },
new Fornecedores { Id = 259, Nome = "Tecovel", Ativo = true },
new Fornecedores { Id = 260, Nome = "Quatro Mares", Ativo = true },
new Fornecedores { Id = 261, Nome = "Camil", Ativo = true },
new Fornecedores { Id = 262, Nome = "Rubi", Ativo = true },
new Fornecedores { Id = 263, Nome = "lIDERANÇA", Ativo = true },
new Fornecedores { Id = 264, Nome = "CRS", Ativo = true },
new Fornecedores { Id = 265, Nome = "Vinc. Campestre", Ativo = true },
new Fornecedores { Id = 266, Nome = "Emulzint", Ativo = true },
new Fornecedores { Id = 267, Nome = "Com. de Fosforo São Luis", Ativo = true },
new Fornecedores { Id = 268, Nome = "Colonial", Ativo = true },
new Fornecedores { Id = 269, Nome = "Memphs", Ativo = true },
new Fornecedores { Id = 270, Nome = "Interfood", Ativo = true },
new Fornecedores { Id = 271, Nome = "Heinz Brasil", Ativo = true },
new Fornecedores { Id = 272, Nome = "Bs Distribuidora", Ativo = true },
new Fornecedores { Id = 273, Nome = "Melita", Ativo = true },
new Fornecedores { Id = 274, Nome = "Peixoto", Ativo = true },
new Fornecedores { Id = 275, Nome = "Bivolt", Ativo = true },
new Fornecedores { Id = 276, Nome = "Val Alimentos", Ativo = true },
new Fornecedores { Id = 277, Nome = "Braulio", Ativo = true },
new Fornecedores { Id = 278, Nome = "Carballo Faro", Ativo = true },
new Fornecedores { Id = 279, Nome = "Sanremo", Ativo = true },
new Fornecedores { Id = 280, Nome = "Wayna", Ativo = true },
new Fornecedores { Id = 281, Nome = "Maritima", Ativo = true },
new Fornecedores { Id = 282, Nome = "Colgate", Ativo = true },
new Fornecedores { Id = 283, Nome = "Pingo Quente", Ativo = true },
new Fornecedores { Id = 284, Nome = "Lavioletera", Ativo = true },
new Fornecedores { Id = 285, Nome = "Arroz Fazenda", Ativo = true },
new Fornecedores { Id = 286, Nome = "Saralee", Ativo = true },
new Fornecedores { Id = 288, Nome = "Laticinio Resende", Ativo = true },
new Fornecedores { Id = 289, Nome = "frisa", Ativo = true },
new Fornecedores { Id = 290, Nome = "Comercial Macedo", Ativo = true },
new Fornecedores { Id = 291, Nome = "Vilma Alimentos", Ativo = true },
new Fornecedores { Id = 292, Nome = "Ebba", Ativo = true },
new Fornecedores { Id = 293, Nome = "Copobras", Ativo = true },
new Fornecedores { Id = 294, Nome = "Flora", Ativo = true },
new Fornecedores { Id = 295, Nome = "Marguti Matias", Ativo = true },
new Fornecedores { Id = 296, Nome = "Manufarura King", Ativo = true },
new Fornecedores { Id = 297, Nome = "cosme e damiao", Ativo = true },
new Fornecedores { Id = 298, Nome = "Rivoli", Ativo = true },
new Fornecedores { Id = 299, Nome = "Alberto Belesso", Ativo = true },
new Fornecedores { Id = 300, Nome = "Silfer", Ativo = true },
new Fornecedores { Id = 301, Nome = "Strech", Ativo = true },
new Fornecedores { Id = 302, Nome = "Plaschio", Ativo = true },
new Fornecedores { Id = 303, Nome = "Garoto", Ativo = true },
new Fornecedores { Id = 304, Nome = "Vida", Ativo = true },
new Fornecedores { Id = 305, Nome = "Peterfruti", Ativo = true },
new Fornecedores { Id = 306, Nome = "Neri Pescados", Ativo = true },
new Fornecedores { Id = 307, Nome = "Olima", Ativo = true },
new Fornecedores { Id = 308, Nome = "Girocamp", Ativo = true },
new Fornecedores { Id = 309, Nome = "Macropac", Ativo = true },
new Fornecedores { Id = 310, Nome = "SCHIN", Ativo = true },
new Fornecedores { Id = 311, Nome = "Mae Terra", Ativo = true },
new Fornecedores { Id = 312, Nome = "Massas Leve", Ativo = true },
new Fornecedores { Id = 313, Nome = "Rildo", Ativo = true },
new Fornecedores { Id = 314, Nome = "Tramontina", Ativo = true },
new Fornecedores { Id = 315, Nome = "Plasvale", Ativo = true },
new Fornecedores { Id = 316, Nome = "JC Reis", Ativo = true },
new Fornecedores { Id = 317, Nome = "Lima e Pergher", Ativo = true },
new Fornecedores { Id = 318, Nome = "Campari", Ativo = true },
new Fornecedores { Id = 319, Nome = "Cescom", Ativo = true },
new Fornecedores { Id = 320, Nome = "Angelo Aurichio", Ativo = true },
new Fornecedores { Id = 321, Nome = "Karamelo", Ativo = true },
new Fornecedores { Id = 322, Nome = "Antonio Basso", Ativo = true },
new Fornecedores { Id = 323, Nome = "Jucineide", Ativo = true },
new Fornecedores { Id = 324, Nome = "Hypermarcas", Ativo = true },
new Fornecedores { Id = 325, Nome = "Fugini", Ativo = true },
new Fornecedores { Id = 326, Nome = "Cafe Paqueta", Ativo = true },
new Fornecedores { Id = 327, Nome = "Dissulba", Ativo = true },
new Fornecedores { Id = 328, Nome = "Maria Rosa", Ativo = true },
new Fornecedores { Id = 329, Nome = "Dimix", Ativo = true },
new Fornecedores { Id = 330, Nome = "Gameleira", Ativo = true },
new Fornecedores { Id = 331, Nome = "Lighsweet", Ativo = true },
new Fornecedores { Id = 332, Nome = "Santa Fé", Ativo = true },
new Fornecedores { Id = 333, Nome = "Paperclin", Ativo = true },
new Fornecedores { Id = 334, Nome = "EB Ciso", Ativo = true },
new Fornecedores { Id = 335, Nome = "Leitissimo", Ativo = true },
new Fornecedores { Id = 336, Nome = "Hersheys", Ativo = true },
new Fornecedores { Id = 337, Nome = "LR Nordeste", Ativo = true },
new Fornecedores { Id = 338, Nome = "Inaceres", Ativo = true },
new Fornecedores { Id = 339, Nome = "Concord", Ativo = true },
new Fornecedores { Id = 340, Nome = "Dell", Ativo = true },
new Fornecedores { Id = 341, Nome = "Sost", Ativo = true },
new Fornecedores { Id = 342, Nome = "Viti Vinicola", Ativo = true },
new Fornecedores { Id = 343, Nome = "Byg Transequip", Ativo = true },
new Fornecedores { Id = 344, Nome = "Dismarina", Ativo = true },
new Fornecedores { Id = 345, Nome = "HL", Ativo = true },
new Fornecedores { Id = 346, Nome = "Vigor", Ativo = true },
new Fornecedores { Id = 347, Nome = "Usina", Ativo = true },
new Fornecedores { Id = 348, Nome = "Porto Frio", Ativo = true },
new Fornecedores { Id = 349, Nome = "Rairon", Ativo = true },
new Fornecedores { Id = 350, Nome = "Alukenti", Ativo = true },
new Fornecedores { Id = 351, Nome = "Prontu", Ativo = true },
new Fornecedores { Id = 352, Nome = "Tambau", Ativo = true },
new Fornecedores { Id = 353, Nome = "Frade", Ativo = true },
new Fornecedores { Id = 354, Nome = "Translitoral", Ativo = true },
new Fornecedores { Id = 355, Nome = "Agis", Ativo = true },
new Fornecedores { Id = 356, Nome = "Goias Minas", Ativo = true },
new Fornecedores { Id = 357, Nome = "Normando", Ativo = true },
new Fornecedores { Id = 358, Nome = "Fante", Ativo = true },
new Fornecedores { Id = 359, Nome = "Tok Comercial", Ativo = true },
new Fornecedores { Id = 360, Nome = "Diversey", Ativo = true },
new Fornecedores { Id = 361, Nome = "Robson Matos", Ativo = true },
new Fornecedores { Id = 362, Nome = "Globalbev", Ativo = true },
new Fornecedores { Id = 363, Nome = "DPC", Ativo = true },
new Fornecedores { Id = 364, Nome = "Santa Amalia", Ativo = true },
new Fornecedores { Id = 365, Nome = "Casa Aladim", Ativo = true },
new Fornecedores { Id = 366, Nome = "Evolusom", Ativo = true },
new Fornecedores { Id = 367, Nome = "Moinhos Unidos", Ativo = true },
new Fornecedores { Id = 368, Nome = "VCT", Ativo = true },
new Fornecedores { Id = 369, Nome = "Polo", Ativo = true },
new Fornecedores { Id = 370, Nome = "Garra", Ativo = true },
new Fornecedores { Id = 371, Nome = "Ducoco", Ativo = true },
new Fornecedores { Id = 372, Nome = "Regina", Ativo = true },
new Fornecedores { Id = 373, Nome = "Deraldo", Ativo = true },
new Fornecedores { Id = 374, Nome = "Jasmine", Ativo = true },
new Fornecedores { Id = 375, Nome = "Conservas Luca", Ativo = true },
new Fornecedores { Id = 376, Nome = "peja", Ativo = true },
new Fornecedores { Id = 377, Nome = "Cromo Steel", Ativo = true },
new Fornecedores { Id = 378, Nome = "Oiapok", Ativo = true },
new Fornecedores { Id = 379, Nome = "Bonduelle", Ativo = true },
new Fornecedores { Id = 380, Nome = "Plus Vita", Ativo = true },
new Fornecedores { Id = 381, Nome = "Pet Car", Ativo = true },
new Fornecedores { Id = 382, Nome = "Damare", Ativo = true },
new Fornecedores { Id = 383, Nome = "Bahia Flex", Ativo = true },
new Fornecedores { Id = 384, Nome = "Genival", Ativo = true },
new Fornecedores { Id = 385, Nome = "Rio do Engenho", Ativo = true },
new Fornecedores { Id = 386, Nome = "Aurora", Ativo = true },
new Fornecedores { Id = 387, Nome = "Qualiflex", Ativo = true },
new Fornecedores { Id = 388, Nome = "Charque 2000", Ativo = true },
new Fornecedores { Id = 389, Nome = "Guss", Ativo = true },
new Fornecedores { Id = 390, Nome = "Agric.Fraiburgo", Ativo = true },
new Fornecedores { Id = 391, Nome = "Pitu", Ativo = true },
new Fornecedores { Id = 392, Nome = "Salton", Ativo = true },
new Fornecedores { Id = 393, Nome = "Cabral e Souza", Ativo = true },
new Fornecedores { Id = 394, Nome = "Polenghi", Ativo = true },
new Fornecedores { Id = 395, Nome = "Six do Brasil", Ativo = true },
new Fornecedores { Id = 396, Nome = "Miolo", Ativo = true },
new Fornecedores { Id = 397, Nome = "CRS Brands", Ativo = true },
new Fornecedores { Id = 398, Nome = "Multi Mercantes", Ativo = true },
new Fornecedores { Id = 399, Nome = "Plastivac", Ativo = true },
new Fornecedores { Id = 400, Nome = "RP Distribuidora", Ativo = true },
new Fornecedores { Id = 401, Nome = "Coveli", Ativo = true },
new Fornecedores { Id = 402, Nome = "Hemmer", Ativo = true },
new Fornecedores { Id = 403, Nome = "Araujo", Ativo = true },
new Fornecedores { Id = 404, Nome = "Mecatec", Ativo = true },
new Fornecedores { Id = 405, Nome = "Schioppa", Ativo = true },
new Fornecedores { Id = 406, Nome = "Ondunort", Ativo = true },
new Fornecedores { Id = 407, Nome = "Dalton Vinhaes", Ativo = true },
new Fornecedores { Id = 408, Nome = "Granforte", Ativo = true },
new Fornecedores { Id = 409, Nome = "Disalli", Ativo = true },
new Fornecedores { Id = 410, Nome = "Reserva de Minas", Ativo = true },
new Fornecedores { Id = 411, Nome = "Teka", Ativo = true },
new Fornecedores { Id = 412, Nome = "M&M", Ativo = true },
new Fornecedores { Id = 413, Nome = "Attuale", Ativo = true },
new Fornecedores { Id = 414, Nome = "Swedish", Ativo = true },
new Fornecedores { Id = 415, Nome = "Sol Embalagens", Ativo = true },
new Fornecedores { Id = 416, Nome = "Olvebra", Ativo = true },
new Fornecedores { Id = 417, Nome = "Pastificio Bahia", Ativo = true },
new Fornecedores { Id = 418, Nome = "Professional Clean", Ativo = true },
new Fornecedores { Id = 419, Nome = "Queijos finos", Ativo = true },
new Fornecedores { Id = 420, Nome = "Emporio", Ativo = true },
new Fornecedores { Id = 421, Nome = "JF Agropecuaria", Ativo = true },
new Fornecedores { Id = 422, Nome = "Jolly", Ativo = true },
new Fornecedores { Id = 423, Nome = "Hikage", Ativo = true },
new Fornecedores { Id = 424, Nome = "Met.Mor", Ativo = true },
new Fornecedores { Id = 425, Nome = "INGERSOLL", Ativo = true },
new Fornecedores { Id = 426, Nome = "LCT", Ativo = true },
new Fornecedores { Id = 427, Nome = "Istambul", Ativo = true },
new Fornecedores { Id = 428, Nome = "RENKS", Ativo = true },
new Fornecedores { Id = 1427, Nome = "JM Camarões", Ativo = true },
new Fornecedores { Id = 1428, Nome = "SPA", Ativo = true },
new Fornecedores { Id = 1429, Nome = "Ubatã", Ativo = true },
new Fornecedores { Id = 1430, Nome = "RCG", Ativo = true },
new Fornecedores { Id = 1431, Nome = "Sulfrios", Ativo = true },
new Fornecedores { Id = 1432, Nome = "ATL", Ativo = true },
new Fornecedores { Id = 1433, Nome = "Frigor Sul", Ativo = true },
new Fornecedores { Id = 1434, Nome = "Pignaton", Ativo = true },
new Fornecedores { Id = 1435, Nome = "Abrace", Ativo = true },
new Fornecedores { Id = 1436, Nome = "Pro embale", Ativo = true },
new Fornecedores { Id = 1437, Nome = "Atacadão", Ativo = true },
new Fornecedores { Id = 1438, Nome = "Itaipava", Ativo = true },
new Fornecedores { Id = 1439, Nome = "Piracanjuba", Ativo = true },
new Fornecedores { Id = 1440, Nome = "Packline", Ativo = true },
new Fornecedores { Id = 1441, Nome = "Maxvac", Ativo = true },
new Fornecedores { Id = 1442, Nome = "Itazul", Ativo = true },
new Fornecedores { Id = 1443, Nome = "Portal das Bebidas", Ativo = true },
new Fornecedores { Id = 1444, Nome = "Frijoa", Ativo = true },
new Fornecedores { Id = 1445, Nome = "Canaã", Ativo = true },
new Fornecedores { Id = 1446, Nome = "GF Baterias", Ativo = true },
new Fornecedores { Id = 1447, Nome = "J Andrade", Ativo = true },
new Fornecedores { Id = 1448, Nome = "SCHIO", Ativo = true },
new Fornecedores { Id = 1449, Nome = "Tercoval", Ativo = true },
new Fornecedores { Id = 1450, Nome = "Otika", Ativo = true },
new Fornecedores { Id = 1451, Nome = "Armazem Top", Ativo = true },
new Fornecedores { Id = 1452, Nome = "LM", Ativo = true },
new Fornecedores { Id = 1453, Nome = "RODTECH", Ativo = true },
new Fornecedores { Id = 1454, Nome = "Terra Boa", Ativo = true },
new Fornecedores { Id = 1455, Nome = "Protervac", Ativo = true },
new Fornecedores { Id = 2455, Nome = "Apis Valverde", Ativo = true },
new Fornecedores { Id = 2456, Nome = "LM Comercio", Ativo = true },
new Fornecedores { Id = 2457, Nome = "Vital", Ativo = true },
new Fornecedores { Id = 2458, Nome = "Soberana", Ativo = true },
new Fornecedores { Id = 2459, Nome = "Ponteland", Ativo = true },
new Fornecedores { Id = 2460, Nome = "Chico do galeto", Ativo = true },
new Fornecedores { Id = 2461, Nome = "M.dias Vitarella", Ativo = true },
new Fornecedores { Id = 2462, Nome = "Samuca", Ativo = true },
new Fornecedores { Id = 2463, Nome = "Portal leste", Ativo = true },
new Fornecedores { Id = 2464, Nome = "Gilmar Licor", Ativo = true },
new Fornecedores { Id = 2465, Nome = "Monte Sion", Ativo = true },
new Fornecedores { Id = 2466, Nome = "Coringa", Ativo = true },
new Fornecedores { Id = 2467, Nome = "Merconplas", Ativo = true },
new Fornecedores { Id = 2468, Nome = "Centauro", Ativo = true },
new Fornecedores { Id = 2469, Nome = "Lumilandia", Ativo = true },
new Fornecedores { Id = 2470, Nome = "Vento", Ativo = true },
new Fornecedores { Id = 2471, Nome = "Dicate", Ativo = true },
new Fornecedores { Id = 2472, Nome = "Licor caseiro", Ativo = true },
new Fornecedores { Id = 2473, Nome = "Dez alimentos", Ativo = true },
new Fornecedores { Id = 3464, Nome = "Licor São Rafael", Ativo = true },
new Fornecedores { Id = 3465, Nome = "Bahiapet", Ativo = true },
new Fornecedores { Id = 3466, Nome = "Moveis k1", Ativo = true },
new Fornecedores { Id = 3467, Nome = "Jetfrio", Ativo = true },
new Fornecedores { Id = 3468, Nome = "MRF", Ativo = true },
new Fornecedores { Id = 3469, Nome = "Fama Doces", Ativo = true },
new Fornecedores { Id = 3470, Nome = "Sorvepan", Ativo = true },
new Fornecedores { Id = 4465, Nome = "THEODORO DARIS", Ativo = true },
new Fornecedores { Id = 4466, Nome = "Piraque", Ativo = true },
new Fornecedores { Id = 4467, Nome = "TESTE - TI", Ativo = true },
new Fornecedores { Id = 4468, Nome = "Top Alto", Ativo = true },
new Fornecedores { Id = 4469, Nome = "Rafael G.Fuchs", Ativo = true },
new Fornecedores { Id = 4470, Nome = "A.G INDUSTRIA", Ativo = true },
new Fornecedores { Id = 4471, Nome = "Cotta Distribuidora", Ativo = true },
new Fornecedores { Id = 4472, Nome = "KM BARROS", Ativo = true },
new Fornecedores { Id = 4473, Nome = "Meneghtti", Ativo = true },
new Fornecedores { Id = 4474, Nome = "Mauro cezar", Ativo = true },
new Fornecedores { Id = 4475, Nome = "ZD Alimentos", Ativo = true },
new Fornecedores { Id = 4476, Nome = "S4A com.equipamentos", Ativo = true },
new Fornecedores { Id = 4477, Nome = "Multinarcas", Ativo = true },
new Fornecedores { Id = 4478, Nome = "Fraccaroli Refrigeracao", Ativo = true },
new Fornecedores { Id = 4480, Nome = "RMR", Ativo = true },
new Fornecedores { Id = 4481, Nome = "Refri-Sylam", Ativo = true },
new Fornecedores { Id = 4482, Nome = "Sanremo", Ativo = true },
new Fornecedores { Id = 4483, Nome = "JACOBS DOUWE RGBERTS", Ativo = true },
new Fornecedores { Id = 4484, Nome = "vale do itajai", Ativo = true },
new Fornecedores { Id = 4485, Nome = "EUROLIFT", Ativo = true },
new Fornecedores { Id = 4486, Nome = "politriz", Ativo = true },
new Fornecedores { Id = 4487, Nome = "Fortline", Ativo = true },
new Fornecedores { Id = 4488, Nome = "Dufrio", Ativo = true },
new Fornecedores { Id = 4489, Nome = "Iotec", Ativo = true },
new Fornecedores { Id = 4490, Nome = "Elebat", Ativo = true },
new Fornecedores { Id = 4491, Nome = "BCM", Ativo = true },
new Fornecedores { Id = 4492, Nome = "Arte Piso", Ativo = true },
new Fornecedores { Id = 4493, Nome = "Megaflex", Ativo = true },
new Fornecedores { Id = 4494, Nome = "Ag Ramos", Ativo = true },
new Fornecedores { Id = 5494, Nome = "Acs", Ativo = true },
new Fornecedores { Id = 5495, Nome = "Frigosul", Ativo = true },
new Fornecedores { Id = 5496, Nome = "Extremo Sul", Ativo = true },
new Fornecedores { Id = 5497, Nome = "SSB", Ativo = true },
new Fornecedores { Id = 5498, Nome = "Wcolortil", Ativo = true },
new Fornecedores { Id = 5499, Nome = "Sensormatic", Ativo = true },
new Fornecedores { Id = 5500, Nome = "Bandeirantes", Ativo = true },
new Fornecedores { Id = 5501, Nome = "R macedo", Ativo = true },
new Fornecedores { Id = 5502, Nome = "Marconi", Ativo = true },
new Fornecedores { Id = 5503, Nome = "Sergio da silva", Ativo = true },
new Fornecedores { Id = 5504, Nome = "Pedro Olimpio", Ativo = true },
new Fornecedores { Id = 5505, Nome = "Dimas", Ativo = true },
new Fornecedores { Id = 5506, Nome = "Baiana Colchões", Ativo = true },
new Fornecedores { Id = 5507, Nome = "Samuel", Ativo = true },
new Fornecedores { Id = 5508, Nome = "Refrigeração Dufrio", Ativo = true },
new Fornecedores { Id = 5509, Nome = "B2w", Ativo = true },
new Fornecedores { Id = 5510, Nome = "JMJ", Ativo = true },
new Fornecedores { Id = 5511, Nome = "Iniltron", Ativo = true },
new Fornecedores { Id = 5512, Nome = "Vitalicio", Ativo = true },
new Fornecedores { Id = 5513, Nome = "Pouso alto", Ativo = true },
new Fornecedores { Id = 5514, Nome = "Mucuri", Ativo = true },
new Fornecedores { Id = 5515, Nome = "Politek", Ativo = true },
new Fornecedores { Id = 5516, Nome = "Fraccaroli", Ativo = true },
new Fornecedores { Id = 5517, Nome = "KHAMEL", Ativo = true },
new Fornecedores { Id = 5518, Nome = "ABC", Ativo = true },
new Fornecedores { Id = 5519, Nome = "Maquiplast", Ativo = true },
new Fornecedores { Id = 5520, Nome = "Vatabom", Ativo = true },
new Fornecedores { Id = 5521, Nome = "Sococo", Ativo = true },
new Fornecedores { Id = 5522, Nome = "Frigerar", Ativo = true },
new Fornecedores { Id = 5523, Nome = "Pirambu", Ativo = true },
new Fornecedores { Id = 5524, Nome = "Higtop", Ativo = true },
new Fornecedores { Id = 5525, Nome = "Leitbom", Ativo = true },
new Fornecedores { Id = 5526, Nome = "Zanini", Ativo = true },
new Fornecedores { Id = 5527, Nome = "Frinense", Ativo = true },
new Fornecedores { Id = 5528, Nome = "Agifort", Ativo = true },
new Fornecedores { Id = 5529, Nome = "Rp Ferreira", Ativo = true },
new Fornecedores { Id = 5530, Nome = "LS dos Reis", Ativo = true },
new Fornecedores { Id = 5531, Nome = "Emvac", Ativo = true },
new Fornecedores { Id = 5532, Nome = "Jonhis", Ativo = true },
new Fornecedores { Id = 5533, Nome = "Incamilho", Ativo = true },
new Fornecedores { Id = 5534, Nome = "Frigoalas", Ativo = true },
new Fornecedores { Id = 5535, Nome = "Subae", Ativo = true },
new Fornecedores { Id = 5536, Nome = "Costa Sul", Ativo = true },
new Fornecedores { Id = 5537, Nome = "Talplastic", Ativo = true },
new Fornecedores { Id = 5538, Nome = "Hitachi", Ativo = true },
new Fornecedores { Id = 5539, Nome = "Qsabor", Ativo = true },
new Fornecedores { Id = 5540, Nome = "Deliso", Ativo = true },
new Fornecedores { Id = 5541, Nome = "Ortobom", Ativo = true },
new Fornecedores { Id = 5542, Nome = "BSB Distribuidora", Ativo = true },
new Fornecedores { Id = 5543, Nome = "Pleno", Ativo = true },
new Fornecedores { Id = 5544, Nome = "Amarildo", Ativo = true },
new Fornecedores { Id = 5545, Nome = "Portela marinho", Ativo = true },
new Fornecedores { Id = 5546, Nome = "Informaster", Ativo = true },
new Fornecedores { Id = 5547, Nome = "Empalux", Ativo = true },
new Fornecedores { Id = 5548, Nome = "Moanil", Ativo = true },
new Fornecedores { Id = 5549, Nome = "Douglas etiquetas", Ativo = true },
new Fornecedores { Id = 5550, Nome = "Capital comercio", Ativo = true },
new Fornecedores { Id = 5551, Nome = "Click", Ativo = true },
new Fornecedores { Id = 5552, Nome = "Paraiso Charque", Ativo = true },
new Fornecedores { Id = 5553, Nome = "Plasticos Zanini", Ativo = true },
new Fornecedores { Id = 6553, Nome = "Scansource", Ativo = true },
new Fornecedores { Id = 6554, Nome = "Inplastic", Ativo = true },
new Fornecedores { Id = 6555, Nome = "Multislim", Ativo = true },
new Fornecedores { Id = 6556, Nome = "Frialy", Ativo = true },
new Fornecedores { Id = 6557, Nome = "carvao Ideal", Ativo = true },
new Fornecedores { Id = 6558, Nome = "Queijos Oriente", Ativo = true },
new Fornecedores { Id = 6559, Nome = "Industrias confiança", Ativo = true },
new Fornecedores { Id = 6560, Nome = "SCP Distribuidora", Ativo = true },
new Fornecedores { Id = 6561, Nome = "N&T", Ativo = true },
new Fornecedores { Id = 6562, Nome = "Sabmiller", Ativo = true },
new Fornecedores { Id = 6563, Nome = "hard", Ativo = true },
new Fornecedores { Id = 6564, Nome = "Luminarias Projeto", Ativo = true },
new Fornecedores { Id = 6565, Nome = "Sandra Suely", Ativo = true },
new Fornecedores { Id = 6566, Nome = "Com. fosforos são roque", Ativo = true },
new Fornecedores { Id = 6567, Nome = "Engetech", Ativo = true },
new Fornecedores { Id = 6568, Nome = "Florismar", Ativo = true },
new Fornecedores { Id = 6569, Nome = "Granpack", Ativo = true },
new Fornecedores { Id = 6570, Nome = "CARAMURU", Ativo = true },
new Fornecedores { Id = 6571, Nome = "New Power", Ativo = true },
new Fornecedores { Id = 6572, Nome = "Sto", Ativo = true },
new Fornecedores { Id = 6573, Nome = "Central embalagens", Ativo = true },
new Fornecedores { Id = 6574, Nome = "Catelan", Ativo = true },
new Fornecedores { Id = 6575, Nome = "Komlog", Ativo = true },
new Fornecedores { Id = 6576, Nome = "Mks", Ativo = true },
new Fornecedores { Id = 6577, Nome = "Termoplast", Ativo = true },
new Fornecedores { Id = 6578, Nome = "Fabricas de vassoura", Ativo = true },
new Fornecedores { Id = 6579, Nome = "LCA", Ativo = true },
new Fornecedores { Id = 6580, Nome = "É10", Ativo = true },
new Fornecedores { Id = 6581, Nome = "AMB", Ativo = true },
new Fornecedores { Id = 6582, Nome = "Prysmiam", Ativo = true },
new Fornecedores { Id = 6583, Nome = "Officer", Ativo = true },
new Fornecedores { Id = 6584, Nome = "READY", Ativo = true },
new Fornecedores { Id = 6585, Nome = "RR Industria", Ativo = true },
new Fornecedores { Id = 6586, Nome = "Bauko", Ativo = true },
new Fornecedores { Id = 6587, Nome = "Salinas", Ativo = true },
new Fornecedores { Id = 6588, Nome = "OKI", Ativo = true },
new Fornecedores { Id = 6589, Nome = "Luzitanea", Ativo = true },
new Fornecedores { Id = 7589, Nome = "Gene", Ativo = true },
new Fornecedores { Id = 7590, Nome = "Multpel", Ativo = true },
new Fornecedores { Id = 7591, Nome = "Real comercial", Ativo = true },
new Fornecedores { Id = 7592, Nome = "Autopel", Ativo = true },
new Fornecedores { Id = 8592, Nome = "Abc de souza", Ativo = true },
new Fornecedores { Id = 8593, Nome = "Laticinio União", Ativo = true },
new Fornecedores { Id = 8594, Nome = "Primecard", Ativo = true },
new Fornecedores { Id = 8595, Nome = "Sunny", Ativo = true },
new Fornecedores { Id = 8596, Nome = "CAF", Ativo = true },
new Fornecedores { Id = 8597, Nome = "sto atacadista", Ativo = true },
new Fornecedores { Id = 9597, Nome = "Manaplast", Ativo = true },
new Fornecedores { Id = 10597, Nome = "Lactalis do Brasil", Ativo = true },
new Fornecedores { Id = 10598, Nome = "Heineken", Ativo = true },
new Fornecedores { Id = 11597, Nome = "Toledo do Brasil", Ativo = true },
new Fornecedores { Id = 11598, Nome = "APALTAGUA BRASIL", Ativo = true },
new Fornecedores { Id = 11599, Nome = "DANICAZIPCO", Ativo = true },
new Fornecedores { Id = 11600, Nome = "I.V.L IND. VIEIRA", Ativo = true },
new Fornecedores { Id = 11601, Nome = "casa doce", Ativo = true },
new Fornecedores { Id = 12597, Nome = "AES IND. DE BISCOITO", Ativo = true },
new Fornecedores { Id = 13597, Nome = "zinho alimentos", Ativo = true },
new Fornecedores { Id = 13598, Nome = "Nordeste frios", Ativo = true },
new Fornecedores { Id = 13599, Nome = "Limiar", Ativo = true },
new Fornecedores { Id = 13600, Nome = "3g soluções", Ativo = true },
new Fornecedores { Id = 13601, Nome = "Forno de minas", Ativo = true },
new Fornecedores { Id = 13602, Nome = "Fazenda bela vista", Ativo = true },
new Fornecedores { Id = 13603, Nome = "Visual", Ativo = true },
new Fornecedores { Id = 13604, Nome = "Luc service", Ativo = true },
new Fornecedores { Id = 13605, Nome = "Cepera", Ativo = true },
new Fornecedores { Id = 14597, Nome = "Fast gondulas", Ativo = true },
new Fornecedores { Id = 14598, Nome = "Alpatagua", Ativo = true },
new Fornecedores { Id = 14599, Nome = "Ingram", Ativo = true },
new Fornecedores { Id = 14600, Nome = "BONNEVILLE", Ativo = true },
new Fornecedores { Id = 14601, Nome = "Fitoherb", Ativo = true },
new Fornecedores { Id = 14602, Nome = "Qualyvac", Ativo = true },
new Fornecedores { Id = 14603, Nome = "NAGÔ", Ativo = true },
new Fornecedores { Id = 15603, Nome = "Qualypac", Ativo = true },
new Fornecedores { Id = 15604, Nome = "Conexão", Ativo = true },
new Fornecedores { Id = 15605, Nome = "ICPA", Ativo = true },
new Fornecedores { Id = 15606, Nome = "Marata", Ativo = true },
new Fornecedores { Id = 15607, Nome = "MD", Ativo = true },
new Fornecedores { Id = 15608, Nome = "Demello", Ativo = true },
new Fornecedores { Id = 15609, Nome = "Bisc.Soares", Ativo = true },
new Fornecedores { Id = 15610, Nome = "Elgin", Ativo = true },
new Fornecedores { Id = 16610, Nome = "Rio forte", Ativo = true },
new Fornecedores { Id = 17610, Nome = "Mundo do vinho", Ativo = true },
new Fornecedores { Id = 17611, Nome = "Perlima", Ativo = true },
new Fornecedores { Id = 17612, Nome = "Laticinio Econata", Ativo = true },
new Fornecedores { Id = 17613, Nome = "Caroba frios", Ativo = true },
new Fornecedores { Id = 17614, Nome = "Lagubras", Ativo = true },
new Fornecedores { Id = 17615, Nome = "Lider", Ativo = true },
new Fornecedores { Id = 17616, Nome = "Color book", Ativo = true },
new Fornecedores { Id = 17617, Nome = "Opergel", Ativo = true },
new Fornecedores { Id = 17618, Nome = "Frugal", Ativo = true },
new Fornecedores { Id = 17619, Nome = "Johnson", Ativo = true },
new Fornecedores { Id = 17620, Nome = "Seculacre", Ativo = true },
new Fornecedores { Id = 17621, Nome = "Panamerica", Ativo = true },
new Fornecedores { Id = 17622, Nome = "FORT PALLETS", Ativo = true },
new Fornecedores { Id = 17623, Nome = "METQ", Ativo = true },
new Fornecedores { Id = 17624, Nome = "CMP", Ativo = true },
new Fornecedores { Id = 17625, Nome = "JC", Ativo = true },
new Fornecedores { Id = 17626, Nome = "Guimaraes", Ativo = true },
new Fornecedores { Id = 17627, Nome = "Rosiely", Ativo = true },
new Fornecedores { Id = 17628, Nome = "Bravo caminhoes", Ativo = true },
new Fornecedores { Id = 17629, Nome = "Fertguss", Ativo = true },
new Fornecedores { Id = 17630, Nome = "Casapratil", Ativo = true },
new Fornecedores { Id = 17631, Nome = "Rio Bahia", Ativo = true },
new Fornecedores { Id = 17632, Nome = "Hortus", Ativo = true },
new Fornecedores { Id = 17633, Nome = "Hypera", Ativo = true },
new Fornecedores { Id = 17634, Nome = "inst são jorge", Ativo = true },
new Fornecedores { Id = 17635, Nome = "Lat. Madalena", Ativo = true },
new Fornecedores { Id = 17636, Nome = "Sugar power", Ativo = true },
new Fornecedores { Id = 17637, Nome = "0", Ativo = true },
            };

            return Json(DataSourceLoader.Load(fornecedores, loadOptions));
        }

        [HttpPost]
        public IActionResult Post(string values) {
            var model = new Fornecedores();
            var _values = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, _values);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            var result = _context.Fornecedores.Add(model);
            _context.SaveChanges();

            return Json(result.Entity.Id);
        }

        [HttpPut]
        public IActionResult Put(int key, string values) {
            var model = _context.Fornecedores.FirstOrDefault(item => item.Id == key);
            if(model == null)
                return StatusCode(409, "Fornecedores not found");

            var _values = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, _values);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            _context.SaveChanges();
            return Ok();
        }

        [HttpDelete]
        public void Delete(int key) {
            var model = _context.Fornecedores.FirstOrDefault(item => item.Id == key);

            _context.Fornecedores.Remove(model);
            _context.SaveChanges();
        }


        private void PopulateModel(Fornecedores model, IDictionary values) {
            string ID = nameof(Fornecedores.Id);
            string NOME = nameof(Fornecedores.Nome);
            string ATIVO = nameof(Fornecedores.Ativo);

            if(values.Contains(ID)) {
                model.Id = Convert.ToInt32(values[ID]);
            }

            if(values.Contains(NOME)) {
                model.Nome = Convert.ToString(values[NOME]);
            }

            if(values.Contains(ATIVO)) {
                model.Ativo = Convert.ToBoolean(values[ATIVO]);
            }
        }

        private string GetFullErrorMessage(ModelStateDictionary modelState) {
            var messages = new List<string>();

            foreach(var entry in modelState) {
                foreach(var error in entry.Value.Errors)
                    messages.Add(error.ErrorMessage);
            }

            return String.Join(" ", messages);
        }
    }
}